import type { Producer, Location, FAQItem } from "./types"

export const mockProducers: Producer[] = [
  {
    id: "prod_berries_rojas_01",
    name: "Berries Rojas",
    farmName: "Huerto La Capilla",
    location: "Guadalajara, Jalisco, México",
    coordinates: {
      lat: 20.6736,
      lng: -103.344,
    },
    certifications: ["CLASE A", "RFC2544", "Y1465", "ISO 9001"],
    category: "Berries",
    batches: [
      {
        id: "batch_2A47JK",
        code: "2A47JK",
        productName: "Berries Rojas Mixtas",
        fabricationDate: "2022-09-20",
        registeredAt: "2022-09-21T10:15:00Z",
        fabricationPlace: "Capilla de Milpillas, Jalisco. 12,000 elementos en este lote.",
        tags: ["Orgánico", "Exportación", "Libre de pesticidas"],
      },
    ],
    products: [
      {
        id: "prod_strawberry_01",
        name: "Fresa",
        description: "Fresas cosechadas todos los días",
        unit: "bandeja",
        packageSize: "250g",
        available: true,
      },
      {
        id: "prod_blueberry_01",
        name: "Mora Azul",
        description: "100g en empaque resellable",
        unit: "bandeja",
        packageSize: "100g",
        available: true,
      },
      {
        id: "prod_raspberry_01",
        name: "Frambuesa",
        description: "1 kg a granel",
        unit: "kg",
        packageSize: "1kg",
        available: false,
      },
      {
        id: "prod_grape_01",
        name: "Uva",
        description: "Solo en temporada",
        unit: "kg",
        packageSize: "500g",
        available: false,
      },
      {
        id: "prod_raisins_01",
        name: "Pasas",
        description: "Pasas por tu casa",
        unit: "bolsa",
        packageSize: "200g",
        available: true,
      },
    ],
  },
  {
    id: "prod_huerta_verde_02",
    name: "Huerta Verde",
    farmName: "Rancho El Paraíso",
    location: "Tepatitlán, Jalisco, México",
    coordinates: {
      lat: 20.8166,
      lng: -102.7666,
    },
    certifications: ["Orgánico Certificado", "Global GAP", "USDA Organic"],
    category: "Verduras",
    batches: [
      {
        id: "batch_VRD9K2",
        code: "VRD9K2",
        productName: "Mix de Verduras Orgánicas",
        fabricationDate: "2024-01-15",
        registeredAt: "2024-01-16T08:30:00Z",
        fabricationPlace: "Tepatitlán, Jalisco. 8,500 elementos en este lote.",
        tags: ["Orgánico", "Sin pesticidas", "Local"],
      },
    ],
    products: [
      {
        id: "prod_lettuce_01",
        name: "Lechuga Romana",
        description: "Fresca y crujiente",
        unit: "pieza",
        packageSize: "1 pieza",
        available: true,
      },
      {
        id: "prod_tomato_01",
        name: "Tomate Cherry",
        description: "Dulce y jugoso",
        unit: "bandeja",
        packageSize: "500g",
        available: true,
      },
      {
        id: "prod_cucumber_01",
        name: "Pepino",
        description: "Hidratante y fresco",
        unit: "kg",
        packageSize: "1kg",
        available: true,
      },
    ],
  },
  {
    id: "prod_citricos_del_valle_03",
    name: "Cítricos del Valle",
    farmName: "Hacienda Los Naranjos",
    location: "Autlán, Jalisco, México",
    coordinates: {
      lat: 19.7723,
      lng: -104.3649,
    },
    certifications: ["SENASICA", "México Calidad Suprema", "ISO 22000"],
    category: "Frutas",
    batches: [
      {
        id: "batch_CTR4L8",
        code: "CTR4L8",
        productName: "Cítricos Premium",
        fabricationDate: "2024-02-10",
        registeredAt: "2024-02-11T09:00:00Z",
        fabricationPlace: "Autlán, Jalisco. 15,000 elementos en este lote.",
        tags: ["Premium", "Exportación", "Sin químicos"],
      },
    ],
    products: [
      {
        id: "prod_orange_01",
        name: "Naranja Valencia",
        description: "Jugosa y dulce",
        unit: "kg",
        packageSize: "2kg",
        available: true,
      },
      {
        id: "prod_lemon_01",
        name: "Limón Persa",
        description: "Rico en vitamina C",
        unit: "kg",
        packageSize: "1kg",
        available: true,
      },
      {
        id: "prod_mandarin_01",
        name: "Mandarina",
        description: "Fácil de pelar",
        unit: "kg",
        packageSize: "1.5kg",
        available: false,
      },
    ],
  },
  {
    id: "prod_agro_organico_04",
    name: "Agro Orgánico",
    farmName: "Granja Sustentable",
    location: "Lagos de Moreno, Jalisco",
    coordinates: {
      lat: 21.3558,
      lng: -101.9207,
    },
    certifications: ["100% Orgánico", "Fair Trade", "Carbono Neutral"],
    category: "Orgánicos",
    batches: [
      {
        id: "batch_ORG5M3",
        code: "ORG5M3",
        productName: "Productos Orgánicos Mixtos",
        fabricationDate: "2024-01-20",
        registeredAt: "2024-01-21T07:45:00Z",
        fabricationPlace: "Lagos de Moreno, Jalisco. 6,000 elementos en este lote.",
        tags: ["Orgánico", "Sustentable", "Comercio Justo"],
      },
    ],
    products: [
      {
        id: "prod_kale_01",
        name: "Kale Orgánico",
        description: "Superalimento verde",
        unit: "manojo",
        packageSize: "200g",
        available: true,
      },
      {
        id: "prod_spinach_01",
        name: "Espinaca Baby",
        description: "Tierna y nutritiva",
        unit: "bolsa",
        packageSize: "300g",
        available: true,
      },
      {
        id: "prod_carrot_01",
        name: "Zanahoria Orgánica",
        description: "Dulce y crocante",
        unit: "kg",
        packageSize: "1kg",
        available: true,
      },
    ],
  },
  {
    id: "prod_tropical_fruits_05",
    name: "Frutas Tropicales",
    farmName: "Finca El Edén",
    location: "Tomatlán, Jalisco",
    coordinates: {
      lat: 19.9333,
      lng: -105.25,
    },
    certifications: ["Rainforest Alliance", "Producto de México", "ISO 9001"],
    category: "Frutas",
    batches: [
      {
        id: "batch_TRP7N9",
        code: "TRP7N9",
        productName: "Mix Tropical",
        fabricationDate: "2024-02-05",
        registeredAt: "2024-02-06T10:20:00Z",
        fabricationPlace: "Tomatlán, Jalisco. 10,000 elementos en este lote.",
        tags: ["Tropical", "Exótico", "Fresco"],
      },
    ],
    products: [
      {
        id: "prod_mango_01",
        name: "Mango Ataulfo",
        description: "El mango más dulce",
        unit: "kg",
        packageSize: "2kg",
        available: true,
      },
      {
        id: "prod_papaya_01",
        name: "Papaya Maradol",
        description: "Rica en enzimas digestivas",
        unit: "pieza",
        packageSize: "1 pieza",
        available: true,
      },
      {
        id: "prod_pineapple_01",
        name: "Piña",
        description: "Dulce y aromática",
        unit: "pieza",
        packageSize: "1 pieza",
        available: false,
      },
    ],
  },
]

export const mockNearbyLocations: Location[] = [
  {
    id: "store_abarrotes_lim",
    name: "Abarrotes Lim",
    type: "tienda",
    distanceKm: 0.6,
    coordinates: { lat: 20.675, lng: -103.343 },
  },
  {
    id: "store_mercado_san",
    name: "Mercado San",
    type: "mercado",
    distanceKm: 1.2,
    coordinates: { lat: 20.671, lng: -103.347 },
  },
  {
    id: "store_aurrera",
    name: "Aurrera",
    type: "supermercado",
    distanceKm: 2.1,
    coordinates: { lat: 20.668, lng: -103.34 },
  },
  {
    id: "store_oxxo",
    name: "Oxxo",
    type: "tienda_conveniencia",
    distanceKm: 0.3,
    coordinates: { lat: 20.673, lng: -103.349 },
  },
]

export const mockFAQs: FAQItem[] = [
  {
    id: "faq_why",
    question: "¿Por qué hacemos esto?",
    answer: "Buscamos mantener transparencia en lo que compramos, desde el origen hasta el punto de venta.",
  },
  {
    id: "faq_why_important",
    question: "¿Por qué es importante?",
    answer: "Para llegar a más clientes y competir con el mercado global con información confiable.",
  },
  {
    id: "faq_how",
    question: "¿Cómo lo hacemos?",
    answer: "Manteniendo la información al alcance de todos mediante códigos QR y trazabilidad digital.",
  },
]
